### ISSUE TITLE
Infinite score issue

### ISSUE THREAD

**Issue by 20026216** [NM-TAFE/github-group-activity-team-6#8]
Once someone has won, if you keep pressing the cells, you can keep winning. The board resets only on reset game, but they will keep the increased score

**Comment by 20026216** [comment]
I did this fix, I FIXED IT, add bandaid fix, add boolean check if the scores were updated

**Comment by 20026216** [comment]
yo this thing still doesn't work!!!! L+ratio

**Comment by kangaroo-eating-carrots** [comment]
The problem is from incremental count in 'check_winner' method in game_play. As the check_winner was used to check whether to keep doing the game(not winner and not draw) and also in index to send the winner information to html. 

I have fixed as additional property whether the check_winner method needs to add the score to the winner or not.  Also, add score property and method in Player class so do not need to have another class.

**Comment by 20026216** [comment]
This guy has a bigger brain than the other guy, Massive W, very cool
